version: '3.1'
 
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
          - 8080:80
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: test
        networks:
            - wordpress-network
    wordpress:
        image: wordpress
        container_name: wordpress
        ports:
          - "8081:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wordpress/wp_html:/var/www/html
        networks:
            - wordpress-network
        depends_on:
            - db
    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./wordpress/database:/var/lib/mysql
        networks:
            - wordpress-network
networks:
    wordpress-network:
        driver: bridge